# baseURL = "https://bennytek.net/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Bennytek's Website"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Bennytek"
  headline = "Hi, it's nice to meet you :)"
  image = "me.png"  # path relative to static directory

  links = [
    # { email = "mailto:hello@your_domain.com" },
    { link = { href = "https://blog.bennytek.net", text = "Blog" } },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/Bennytek" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    { instagram = "https://instagram.com/Bennytek" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    { lastfm = "https://www.last.fm/user/Bennytek" },
    # { linkedin = "https://linkedin.com/in/username" },
    { mastodon = "https://aus.social/@Bennytek" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
	{ spotify = { href = "https://open.spotify.com/user/zr3pgugp68s0ysv4azmgmwiza", text = "Spotify" } },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    { steam = "https://steamcommunity.com/id/Bennytek/" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@Bennytek" },
    # { tumblr = "https://username.tumblr.com" },
    { twitch = "https://twitch.tv/Bennyttek" },
    { twitter = "https://twitter.com/Bennyttek" },
    # { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://youtube.com/Bennytek" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
